# Generated by Django 5.2.16 on 2026-07-30 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OFFICIAL_WEBSITE", "Official website"),
                            ("FACULTY_WEBSITE", "Faculty website"),
                            ("STUDENT_ORGANIZATION_WEBSITE", "Student organization website"),
                            ("PUBLIC_SOCIAL_ACCOUNT", "Public social account"),
                            ("PUBLIC_CHANNEL", "Public channel"),
                            ("MANUAL", "Manual"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("base_url", models.URLField(blank=True, max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("crawl_frequency", models.CharField(blank=True, max_length=100)),
                ("last_successful_crawl_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_crawl_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_reliability",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
                ),
                ("adapter_key", models.CharField(max_length=100)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sources",
                        to="organizers.organizer",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("items_discovered", models.PositiveIntegerField(default=0)),
                ("items_processed", models.PositiveIntegerField(default=0)),
                ("error_type", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=128)),
                ("worker_version", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crawl_runs",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="SourceRepresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_identifier", models.CharField(max_length=512)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representations",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "external_identifier"),
            },
        ),
        migrations.CreateModel(
            name="RawSourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fetched_at", models.DateTimeField()),
                ("storage_key", models.CharField(max_length=1000, unique=True)),
                ("content_hash", models.CharField(db_index=True, max_length=128)),
                ("language", models.CharField(blank=True, max_length=20)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "crawl_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_documents",
                        to="sources.crawlrun",
                    ),
                ),
                (
                    "source_representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_documents",
                        to="sources.sourcerepresentation",
                    ),
                ),
            ],
            options={
                "ordering": ("-fetched_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="sourcerepresentation",
            constraint=models.UniqueConstraint(
                fields=("source", "external_identifier"), name="unique_source_external_identifier"
            ),
        ),
    ]
