# Generated by Django 5.2.16 on 2026-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizers", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="crawlrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("completed_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="crawl_completed_not_before_started",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_reliability__isnull", True),
                    models.Q(("source_reliability__gte", 0), ("source_reliability__lte", 1)),
                    _connector="OR",
                ),
                name="source_reliability_between_zero_and_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerepresentation",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_seen_at__gte", models.F("first_seen_at"))),
                name="representation_last_seen_not_before_first",
            ),
        ),
    ]
