# Generated by Django 5.2.16 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_ingestion_jobs_and_batched_model_invocations"),
        ("sources", "0002_crawlrun_crawl_completed_not_before_started_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlrun",
            name="ingestion_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crawl_runs",
                to="ingestion.ingestionjob",
            ),
        ),
    ]
