# Generated by Django 5.2.16 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


def copy_raw_document_ingestion_jobs(apps, schema_editor):
    raw_source_document = apps.get_model("sources", "RawSourceDocument")
    documents = raw_source_document.objects.filter(
        crawl_run__ingestion_job_id__isnull=False
    ).select_related("crawl_run")
    batch = []
    for document in documents.iterator(chunk_size=500):
        document.ingestion_job_id = document.crawl_run.ingestion_job_id
        batch.append(document)
        if len(batch) == 500:
            raw_source_document.objects.bulk_update(batch, ("ingestion_job",))
            batch.clear()
    if batch:
        raw_source_document.objects.bulk_update(batch, ("ingestion_job",))


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0004_alter_ingestionjob_pipeline_key"),
        ("sources", "0003_crawlrun_ingestion_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawsourcedocument",
            name="ingestion_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_documents",
                to="ingestion.ingestionjob",
            ),
        ),
        migrations.RunPython(
            copy_raw_document_ingestion_jobs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="rawsourcedocument",
            name="crawl_run",
        ),
        migrations.DeleteModel(
            name="CrawlRun",
        ),
    ]
