# Generated by Django 5.2.16 on 2026-07-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                (
                    "organization_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NTU_CENTRAL_UNIT", "NTU central unit"),
                            ("NTU_SCHOOL_COLLEGE", "NTU school or college"),
                            ("NTU_RESEARCH_CENTRE_INSTITUTE", "NTU research centre or institute"),
                            ("NTU_STUDENT_ORGANISATION", "NTU student organisation"),
                            ("NTU_RESIDENTIAL_HALL", "NTU residential hall"),
                            ("EXTERNAL_COMPANY", "External company"),
                            ("GOVERNMENT_PUBLIC_AGENCY", "Government or public agency"),
                            ("NONPROFIT_COMMUNITY", "Nonprofit or community"),
                            ("INDIVIDUAL_INFORMAL", "Individual or informal group"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("school_or_unit", models.CharField(blank=True, max_length=255)),
                ("website_url", models.URLField(blank=True, max_length=1000)),
                ("social_urls", models.JSONField(blank=True, default=list)),
                ("is_official", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
