# Generated by Django 5.2.16 on 2026-07-30 08:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("extractor_type", models.CharField(max_length=100)),
                ("extractor_version", models.CharField(max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_storage_key", models.CharField(blank=True, max_length=1000)),
                ("raw_output_storage_key", models.CharField(blank=True, max_length=1000)),
                ("response_identifier", models.CharField(blank=True, max_length=255)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "raw_source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extraction_runs",
                        to="sources.rawsourcedocument",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="EventCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("candidate_index", models.PositiveSmallIntegerField()),
                ("schema_version", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "overall_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("REVIEW_REQUIRED", "Review required"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_candidates",
                        to="sources.sourcerepresentation",
                    ),
                ),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="ingestion.extractionrun",
                    ),
                ),
            ],
            options={
                "ordering": ("extraction_run_id", "candidate_index"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("extraction_run", "candidate_index"),
                        name="unique_candidate_index_per_extraction",
                    )
                ],
            },
        ),
    ]
