# Generated by Django 5.2.16 on 2026-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("overall_confidence__isnull", True),
                    models.Q(("overall_confidence__gte", 0), ("overall_confidence__lte", 1)),
                    _connector="OR",
                ),
                name="candidate_confidence_between_zero_and_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("completed_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="extraction_completed_not_before_started",
            ),
        ),
    ]
