# Generated by Django 5.2.16 on 2026-08-10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ingestion", "0002_eventcandidate_candidate_confidence_between_zero_and_one_and_more"),
        ("sources", "0002_crawlrun_crawl_completed_not_before_started_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("COMMAND", "Command"),
                            ("SCHEDULE", "Schedule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_key", models.CharField(default="telegram_text", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                ("available_at", models.DateTimeField(db_index=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("worker_id", models.CharField(blank=True, max_length=255)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("items_discovered", models.PositiveIntegerField(default=0)),
                ("items_screened", models.PositiveIntegerField(default=0)),
                ("items_relevant", models.PositiveIntegerField(default=0)),
                ("items_extracted", models.PositiveIntegerField(default=0)),
                ("candidates_created", models.PositiveIntegerField(default=0)),
                ("failures_count", models.PositiveIntegerField(default=0)),
                ("error_type", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="ingestion.ingestionrequest",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_jobs",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(status__in=("QUEUED", "RUNNING")),
                        fields=("source",),
                        name="one_active_ingestion_job_per_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(completed_at__isnull=True)
                        | models.Q(completed_at__gte=models.F("claimed_at")),
                        name="ingestion_job_completed_not_before_claimed",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("SCREENING", "Screening"), ("EXTRACTION", "Extraction")],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="openai", max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=100)),
                ("schema_version", models.CharField(max_length=100)),
                ("batch_index", models.PositiveIntegerField()),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("response_identifier", models.CharField(blank=True, max_length=255)),
                ("input_hash", models.CharField(db_index=True, max_length=128)),
                ("raw_output_storage_key", models.CharField(blank=True, max_length=1000)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("error_type", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="model_invocations",
                        to="ingestion.ingestionjob",
                    ),
                ),
            ],
            options={
                "ordering": ("job_id", "stage", "batch_index", "attempt_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "stage", "batch_index", "attempt_number"),
                        name="unique_model_invocation_attempt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(completed_at__isnull=True)
                        | models.Q(completed_at__gte=models.F("started_at")),
                        name="model_invocation_completed_not_before_started",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="extractionrun",
            name="model_invocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extraction_runs",
                to="ingestion.modelinvocation",
            ),
        ),
        migrations.CreateModel(
            name="MessageScreening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=128)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("EVENT", "Event"),
                            ("UNCERTAIN", "Uncertain"),
                            ("NOT_EVENT", "Not event"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "model_invocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="ingestion.modelinvocation",
                    ),
                ),
                (
                    "raw_source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="sources.rawsourcedocument",
                    ),
                ),
                (
                    "source_representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="sources.sourcerepresentation",
                    ),
                ),
            ],
            options={
                "ordering": ("job_id", "source_representation_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "source_representation"),
                        name="unique_message_screening_per_job",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(confidence__isnull=True)
                        | (models.Q(confidence__gte=0) & models.Q(confidence__lte=1)),
                        name="screening_confidence_between_zero_and_one",
                    ),
                ],
            },
        ),
    ]
