# Generated by Django 5.2.16 on 2026-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0003_ingestion_jobs_and_batched_model_invocations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionjob",
            name="pipeline_key",
            field=models.CharField(max_length=100),
        ),
    ]
