# Generated by Django 5.2.16 on 2026-08-16 08:11

from django.db import migrations, models


def normalize_validation_statuses(apps, schema_editor):
    candidate = apps.get_model("ingestion", "EventCandidate")
    candidate.objects.filter(validation_status="VALID").update(validation_status="READY")
    candidate.objects.filter(validation_status="INVALID").update(
        validation_status="REVIEW_REQUIRED"
    )


def restore_validation_statuses(apps, schema_editor):
    candidate = apps.get_model("ingestion", "EventCandidate")
    candidate.objects.filter(validation_status="READY").update(validation_status="VALID")


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0004_alter_ingestionjob_pipeline_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventcandidate",
            old_name="validation_errors",
            new_name="validation_issues",
        ),
        migrations.AddField(
            model_name="modelinvocation",
            name="reference_data_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="modelinvocation",
            name="reference_data_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(normalize_validation_statuses, restore_validation_statuses),
        migrations.AlterField(
            model_name="eventcandidate",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("READY", "Ready"),
                    ("REVIEW_REQUIRED", "Review required"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
