# Generated by Django 5.2.16 on 2026-08-16 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_eventoccurrence_occurrence_status"),
        ("ingestion", "0005_remove_eventcandidate_validation_errors_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("effective_payload", models.JSONField()),
                ("validation_issues", models.JSONField(blank=True, default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not required"),
                            ("NEEDS_REVIEW", "Needs review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="NEEDS_REVIEW",
                        max_length=30,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("BLOCKED", "Blocked"),
                            ("SYNCED", "Synced"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "promotion_method",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("AUTOMATIC", "Automatic"),
                            ("MANUAL", "Manual"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("allow_duplicate", models.BooleanField(default=False)),
                ("has_manual_edits", models.BooleanField(default=False)),
                ("review_version", models.PositiveIntegerField(default=1)),
                ("synced_version", models.PositiveIntegerField(default=0)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_reviews",
                        to="events.event",
                    ),
                ),
                (
                    "event_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="ingestion.eventcandidate",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="CandidateReviewOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_ref", models.CharField(max_length=100)),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_review_link",
                        to="events.eventoccurrence",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrence_links",
                        to="ingestion.candidatereview",
                    ),
                ),
            ],
            options={
                "ordering": ("review_id", "local_ref"),
            },
        ),
        migrations.CreateModel(
            name="CandidateReviewRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_index", models.PositiveSmallIntegerField()),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_review_link",
                        to="events.registration",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_links",
                        to="ingestion.candidatereview",
                    ),
                ),
            ],
            options={
                "ordering": ("review_id", "source_index"),
            },
        ),
        migrations.AddConstraint(
            model_name="candidatereview",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_version__gte", 1)),
                name="candidate_review_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatereview",
            constraint=models.CheckConstraint(
                condition=models.Q(("synced_version__lte", models.F("review_version"))),
                name="candidate_review_synced_version_not_ahead",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatereviewoccurrence",
            constraint=models.UniqueConstraint(
                fields=("review", "local_ref"), name="unique_occurrence_ref_per_candidate_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatereviewregistration",
            constraint=models.UniqueConstraint(
                fields=("review", "source_index"),
                name="unique_registration_index_per_candidate_review",
            ),
        ),
    ]
