# Generated by Django 5.2.16 on 2026-08-21 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_candidate_and_review_state(apps, schema_editor):
    candidate_model = apps.get_model("ingestion", "EventCandidate")
    review_model = apps.get_model("ingestion", "CandidateReview")
    for candidate in candidate_model.objects.order_by("pk").iterator():
        payload = dict(candidate.payload) if isinstance(candidate.payload, dict) else {}
        payload["schema_version"] = "event-candidate-v3"
        payload.setdefault("observation_type", candidate.observation_type or "UNKNOWN")
        candidate.payload = payload
        candidate.schema_version = "event-candidate-v3"
        candidate.save(update_fields=("payload", "schema_version"))
    for review in review_model.objects.order_by("pk").iterator():
        payload = (
            dict(review.effective_payload) if isinstance(review.effective_payload, dict) else {}
        )
        payload["schema_version"] = "event-candidate-v3"
        payload.setdefault("observation_type", "UNKNOWN")
        title = str(payload.get("title") or "").strip()
        controlled = any(
            isinstance(payload.get(name), dict)
            and bool(payload[name].get("supported_codes") or payload[name].get("other_values"))
            for name in ("formats", "topics", "purposes", "audiences")
        )
        useful = any(
            (
                bool(str(payload.get("description") or "").strip()),
                bool(payload.get("occurrences")),
                bool(payload.get("organizers")),
                bool(payload.get("registrations")),
                controlled,
                bool(payload.get("image_url")),
            )
        )
        if review.review_status == "REJECTED":
            status = "REJECTED"
        elif review.sync_status == "BLOCKED" or not title or not useful:
            status = "BLOCKED"
        else:
            status = "READY"
        review.effective_payload = payload
        review.review_status = status
        review.save(update_fields=("effective_payload", "review_status"))


def restore_candidate_and_review_state(apps, schema_editor):
    candidate_model = apps.get_model("ingestion", "EventCandidate")
    review_model = apps.get_model("ingestion", "CandidateReview")
    for candidate in candidate_model.objects.order_by("pk").iterator():
        payload = dict(candidate.payload) if isinstance(candidate.payload, dict) else {}
        payload["schema_version"] = "event-candidate-v2"
        payload.pop("observation_type", None)
        candidate.payload = payload
        candidate.schema_version = "event-candidate-v2"
        candidate.save(update_fields=("payload", "schema_version"))
    review_model.objects.filter(review_status="READY").update(review_status="NOT_REQUIRED")
    review_model.objects.filter(review_status="BLOCKED").update(review_status="NEEDS_REVIEW")


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_eventrevision_eventsourcelink_and_more"),
        ("ingestion", "0006_candidatereview_candidatereviewoccurrence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("review_version", models.PositiveIntegerField()),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("signals", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("review_id", "review_version", "rank"),
            },
        ),
        migrations.CreateModel(
            name="CanonicalizationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("review_version", models.PositiveIntegerField()),
                ("plan_version", models.PositiveIntegerField(default=1)),
                ("applied_version", models.PositiveIntegerField(default=0)),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[("ADD", "Add"), ("UPDATE", "Update"), ("LINK_ONLY", "Link only")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                            ("STALE", "Stale"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("target_event_updated_at", models.DateTimeField(blank=True, null=True)),
                ("target_snapshot_hash", models.CharField(blank=True, max_length=64)),
                ("match_snapshot", models.JSONField(default=list)),
                ("generated_proposal", models.JSONField(default=dict)),
                ("effective_proposal", models.JSONField(default=dict)),
                ("validation_issues", models.JSONField(default=list)),
                ("domain_flags", models.JSONField(default=list)),
                ("grounding_flags", models.JSONField(default=list)),
                ("has_manual_edits", models.BooleanField(default=False)),
                ("applied_snapshot", models.JSONField(default=dict)),
                ("application_error", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at", "-pk"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="candidatereviewoccurrence",
            name="unique_occurrence_ref_per_candidate_review",
        ),
        migrations.RemoveConstraint(
            model_name="candidatereviewregistration",
            name="unique_registration_index_per_candidate_review",
        ),
        migrations.RemoveField(
            model_name="candidatereviewoccurrence",
            name="occurrence",
        ),
        migrations.RemoveField(
            model_name="candidatereviewoccurrence",
            name="review",
        ),
        migrations.RemoveField(
            model_name="candidatereviewregistration",
            name="registration",
        ),
        migrations.RemoveField(
            model_name="candidatereviewregistration",
            name="review",
        ),
        migrations.RemoveConstraint(
            model_name="candidatereview",
            name="candidate_review_synced_version_not_ahead",
        ),
        migrations.RenameField(
            model_name="candidatereview",
            old_name="synced_version",
            new_name="processed_version",
        ),
        migrations.RemoveField(
            model_name="candidatereview",
            name="allow_duplicate",
        ),
        migrations.RemoveField(
            model_name="candidatereview",
            name="canonical_event",
        ),
        migrations.RemoveField(
            model_name="candidatereview",
            name="last_synced_at",
        ),
        migrations.RemoveField(
            model_name="candidatereview",
            name="promotion_method",
        ),
        migrations.RemoveField(
            model_name="candidatereview",
            name="sync_error",
        ),
        migrations.AddField(
            model_name="eventcandidate",
            name="observation_type",
            field=models.CharField(
                choices=[
                    ("EVENT_ANNOUNCEMENT", "Event announcement"),
                    ("EVENT_FOLLOW_UP", "Event follow-up"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            migrate_candidate_and_review_state,
            restore_candidate_and_review_state,
        ),
        migrations.RemoveField(
            model_name="candidatereview",
            name="sync_status",
        ),
        migrations.AlterField(
            model_name="candidatereview",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("READY", "Ready"),
                    ("BLOCKED", "Blocked"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="modelinvocation",
            name="stage",
            field=models.CharField(
                choices=[
                    ("SCREENING", "Screening"),
                    ("EXTRACTION", "Extraction"),
                    ("CANONICALIZATION", "Canonicalization"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatereview",
            constraint=models.CheckConstraint(
                condition=models.Q(("processed_version__lte", models.F("review_version"))),
                name="candidate_review_processed_version_not_ahead",
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_matches",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="ingestion.candidatereview",
            ),
        ),
        migrations.AddField(
            model_name="canonicalizationplan",
            name="model_invocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="canonicalization_plans",
                to="ingestion.modelinvocation",
            ),
        ),
        migrations.AddField(
            model_name="canonicalizationplan",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="canonicalization_plans",
                to="ingestion.candidatereview",
            ),
        ),
        migrations.AddField(
            model_name="canonicalizationplan",
            name="target_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="canonicalization_plans",
                to="events.event",
            ),
        ),
        migrations.DeleteModel(
            name="CandidateReviewOccurrence",
        ),
        migrations.DeleteModel(
            name="CandidateReviewRegistration",
        ),
        migrations.AddConstraint(
            model_name="candidatematch",
            constraint=models.UniqueConstraint(
                fields=("review", "review_version", "event"),
                name="unique_candidate_match_per_review_version_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatematch",
            constraint=models.UniqueConstraint(
                fields=("review", "review_version", "rank"),
                name="unique_candidate_match_rank_per_review_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatematch",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                name="candidate_match_score_between_zero_and_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalizationplan",
            constraint=models.UniqueConstraint(
                fields=("review", "review_version"),
                name="unique_canonicalization_plan_per_review_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalizationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("plan_version__gte", 1)),
                name="canonicalization_plan_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalizationplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("applied_version__lte", models.F("plan_version"))),
                name="canonicalization_plan_applied_version_not_ahead",
            ),
        ),
    ]
