# Generated by Django 5.2.16 on 2026-07-30 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingestion", "0001_initial"),
        ("organizers", "0001_initial"),
        ("sources", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "label"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "label"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "label"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "event series",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="EventTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "label"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("normalized_title", models.CharField(db_index=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending review"),
                            ("PUBLISHED", "Published"),
                            ("WITHHELD", "Withheld"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("AUTOMATICALLY_VERIFIED", "Automatically verified"),
                            ("MANUALLY_VERIFIED", "Manually verified"),
                            ("CONFLICTING", "Conflicting"),
                        ],
                        default="UNVERIFIED",
                        max_length=30,
                    ),
                ),
                ("image_reference", models.CharField(blank=True, max_length=1000)),
                ("audience_notes", models.TextField(blank=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audiences",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="events.eventaudience"
                    ),
                ),
                (
                    "formats",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="events.eventformat"
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="EventOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "time_precision",
                    models.CharField(
                        choices=[
                            ("EXACT", "Exact"),
                            ("APPROXIMATE", "Approximate"),
                            ("DATE_ONLY", "Date only"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_all_day", models.BooleanField(default=False)),
                ("raw_location_text", models.TextField(blank=True)),
                (
                    "occurrence_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("AVAILABLE", "Available"),
                            ("LIMITED", "Limited"),
                            ("FULL", "Full"),
                            ("WAITLIST", "Waitlist"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date", "start_time", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="EventOrganizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizers.organizer"
                    ),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="events.EventOrganizer",
                to="organizers.organizer",
            ),
        ),
        migrations.CreateModel(
            name="EventProvenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_primary_source", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance",
                        to="events.event",
                    ),
                ),
                (
                    "event_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="canonical_provenance",
                        to="ingestion.eventcandidate",
                    ),
                ),
                (
                    "source_representation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_provenance",
                        to="sources.sourcerepresentation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="purposes",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.eventpurpose"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventseries",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="topics",
            field=models.ManyToManyField(blank=True, related_name="events", to="events.eventtopic"),
        ),
        migrations.CreateModel(
            name="OccurrenceVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.eventoccurrence"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="venues.venue"
                    ),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
        ),
        migrations.AddField(
            model_name="eventoccurrence",
            name="venues",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrences",
                through="events.OccurrenceVenue",
                to="venues.venue",
            ),
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("ATTENDEE", "Attendee"),
                            ("VOLUNTEER", "Volunteer"),
                            ("COMPETITOR", "Competitor"),
                            ("PRESENTER", "Presenter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("opens_date", models.DateField(blank=True, null=True)),
                ("opens_time", models.TimeField(blank=True, null=True)),
                ("closes_date", models.DateField(blank=True, null=True)),
                ("closes_time", models.TimeField(blank=True, null=True)),
                (
                    "time_precision",
                    models.CharField(
                        choices=[
                            ("EXACT", "Exact"),
                            ("APPROXIMATE", "Approximate"),
                            ("DATE_ONLY", "Date only"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("NOT_OPEN", "Not open"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("FULL", "Full"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.eventoccurrence",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.eventseries",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="eventorganizer",
            constraint=models.UniqueConstraint(
                fields=("event", "organizer"), name="unique_organizer_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventorganizer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("event",),
                name="one_primary_organizer_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprovenance",
            constraint=models.UniqueConstraint(
                fields=("event", "source_representation"), name="unique_representation_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprovenance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_source", True)),
                fields=("event",),
                name="one_primary_source_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrencevenue",
            constraint=models.UniqueConstraint(
                fields=("occurrence", "venue"), name="unique_venue_per_occurrence"
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrencevenue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("occurrence",),
                name="one_primary_venue_per_occurrence",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.UniqueConstraint(
                fields=("event", "sequence"), name="unique_occurrence_sequence_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="occurrence_end_date_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True), ("end_date__isnull", False), _connector="OR"
                ),
                name="occurrence_end_time_requires_end_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True), ("start_time__isnull", False), _connector="OR"
                ),
                name="occurrence_end_time_requires_start_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_all_day", False),
                    models.Q(("start_time__isnull", True), ("end_time__isnull", True)),
                    _connector="OR",
                ),
                name="all_day_occurrence_has_no_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gt", models.F("start_date")),
                    ("end_time__isnull", True),
                    ("start_time__isnull", True),
                    ("end_time__gte", models.F("start_time")),
                    _connector="OR",
                ),
                name="same_day_occurrence_end_time_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event__isnull", True),
                        ("occurrence__isnull", True),
                        ("series__isnull", False),
                    ),
                    models.Q(
                        ("event__isnull", False),
                        ("occurrence__isnull", True),
                        ("series__isnull", True),
                    ),
                    models.Q(
                        ("event__isnull", True),
                        ("occurrence__isnull", False),
                        ("series__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="registration_has_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opens_time__isnull", True), ("opens_date__isnull", False), _connector="OR"
                ),
                name="registration_open_time_requires_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closes_time__isnull", True), ("closes_date__isnull", False), _connector="OR"
                ),
                name="registration_close_time_requires_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closes_date__isnull", True),
                    ("opens_date__isnull", True),
                    ("closes_date__gte", models.F("opens_date")),
                    _connector="OR",
                ),
                name="registration_close_date_not_before_open",
            ),
        ),
    ]
