# Generated by Django 5.2.16 on 2026-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_seed_classifications"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closes_date__isnull", True),
                    ("opens_date__isnull", True),
                    ("closes_date__gt", models.F("opens_date")),
                    ("closes_time__isnull", True),
                    ("opens_time__isnull", True),
                    ("closes_time__gte", models.F("opens_time")),
                    _connector="OR",
                ),
                name="same_day_registration_close_not_before_open",
            ),
        ),
    ]
