# Generated by Django 5.2.16 on 2026-08-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_registration_same_day_registration_close_not_before_open"),
        ("venues", "0003_venuealias_venue_alias_confidence_between_zero_and_one"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("time_precision", "EXACT"), _negated=True),
                    ("start_time__isnull", False),
                    _connector="OR",
                ),
                name="exact_occurrence_requires_start_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("time_precision", "DATE_ONLY"), _negated=True),
                    models.Q(("start_time__isnull", True), ("end_time__isnull", True)),
                    _connector="OR",
                ),
                name="date_only_occurrence_has_no_times",
            ),
        ),
    ]
