# Generated by Django 5.2.16 on 2026-08-16 07:21

from django.db import migrations, models


def delete_series_registrations(apps, schema_editor):
    registration = apps.get_model("events", "Registration")
    registration.objects.filter(series__isnull=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventoccurrence_exact_occurrence_requires_start_time_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_series_registrations, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="registration",
            name="registration_has_exactly_one_owner",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="series",
        ),
        migrations.RemoveField(
            model_name="event",
            name="series",
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event__isnull", False), ("occurrence__isnull", True)),
                    models.Q(("event__isnull", True), ("occurrence__isnull", False)),
                    _connector="OR",
                ),
                name="registration_has_exactly_one_owner",
            ),
        ),
        migrations.DeleteModel(
            name="EventSeries",
        ),
    ]
