# Generated by Django 5.2.16 on 2026-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_registration_series_remove_event_series_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoccurrence",
            name="attendance_mode",
            field=models.CharField(
                choices=[
                    ("IN_PERSON", "In person"),
                    ("ONLINE", "Online"),
                    ("HYBRID", "Hybrid"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventoccurrence",
            name="meeting_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
