# Generated by Django 5.2.16 on 2026-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_eventoccurrence_attendance_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoccurrence",
            name="occurrence_status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("SCHEDULED", "Scheduled"),
                    ("POSTPONED", "Postponed"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
