# Generated by Django 5.2.16 on 2026-08-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_eventoccurrence_occurrence_status"),
        ("ingestion", "0006_candidatereview_candidatereviewoccurrence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("before_snapshot", models.JSONField()),
                ("after_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("event_id", "revision_number"),
            },
        ),
        migrations.CreateModel(
            name="EventSourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_primary_source", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="EventObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observation_type", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_observation",
                        to="ingestion.eventcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "pk"),
            },
        ),
    ]
