# Generated by Django 5.2.16 on 2026-08-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_eventrevision_eventsourcelink_and_more"),
        ("ingestion", "0007_candidatematch_canonicalizationplan_and_more"),
        ("sources", "0004_replace_crawl_run_with_ingestion_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrevision",
            name="canonicalization_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_revision",
                to="ingestion.canonicalizationplan",
            ),
        ),
        migrations.AddField(
            model_name="eventrevision",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventsourcelink",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_links",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventsourcelink",
            name="source_representation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_source_links",
                to="sources.sourcerepresentation",
            ),
        ),
        migrations.AddField(
            model_name="eventobservation",
            name="source_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="events.eventsourcelink",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrevision",
            constraint=models.UniqueConstraint(
                fields=("event", "revision_number"), name="unique_revision_number_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsourcelink",
            constraint=models.UniqueConstraint(
                fields=("event", "source_representation"),
                name="unique_source_representation_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsourcelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_source", True)),
                fields=("event",),
                name="one_primary_source_link_per_event",
            ),
        ),
    ]
