# Generated by Django 5.2.16 on 2026-07-30 08:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ("normalized_name", models.CharField(max_length=255, unique=True)),
                (
                    "map_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "campus_area",
                    models.CharField(
                        choices=[
                            ("MAIN", "Main campus"),
                            ("NIE", "NIE"),
                            ("NOVENA", "Novena"),
                            ("OFF_CAMPUS", "Off campus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("official_map_identifier", models.CharField(blank=True, max_length=255)),
                ("official_map_url", models.URLField(blank=True, max_length=1000)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(max_length=255)),
                ("floor", models.CharField(blank=True, max_length=50)),
                ("room_code", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("LECTURE_THEATRE", "Lecture theatre"),
                            ("SEMINAR_ROOM", "Seminar room"),
                            ("CLASSROOM", "Classroom"),
                            ("AUDITORIUM", "Auditorium"),
                            ("LABORATORY", "Laboratory"),
                            ("HALL", "Hall"),
                            ("SPORTS_FACILITY", "Sports facility"),
                            ("OUTDOOR", "Outdoor"),
                            ("ONLINE", "Online"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "map_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("indoor_map_identifier", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="venues.building",
                    ),
                ),
            ],
            options={
                "ordering": ("building__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="VenueAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("alias", models.CharField(max_length=255)),
                ("normalized_alias", models.CharField(db_index=True, max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("EXACT", "Exact"),
                            ("NORMALIZED", "Normalized"),
                            ("ABBREVIATION", "Abbreviation"),
                            ("OBSERVED", "Observed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliases",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("normalized_alias",),
            },
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                fields=("building", "normalized_name"), name="unique_venue_name_per_building"
            ),
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("building__isnull", True)),
                fields=("normalized_name",),
                name="unique_unattached_venue_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="venuealias",
            constraint=models.UniqueConstraint(
                fields=("venue", "normalized_alias"), name="unique_alias_per_venue"
            ),
        ),
    ]
