# Generated by Django 5.2.16 on 2026-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_seed_core_locations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="venuealias",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                    _connector="OR",
                ),
                name="venue_alias_confidence_between_zero_and_one",
            ),
        ),
    ]
