# Generated by Django 5.2.16 on 2026-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0003_venuealias_venue_alias_confidence_between_zero_and_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="venue_type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building"),
                    ("LECTURE_THEATRE", "Lecture theatre"),
                    ("SEMINAR_ROOM", "Seminar room"),
                    ("CLASSROOM", "Classroom"),
                    ("AUDITORIUM", "Auditorium"),
                    ("LABORATORY", "Laboratory"),
                    ("HALL", "Hall"),
                    ("SPORTS_FACILITY", "Sports facility"),
                    ("OUTDOOR", "Outdoor"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
