# Generated by Django 5.2.16 on 2026-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0004_alter_venue_venue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="venuealias",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="venuealias",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="venue_type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building"),
                    ("LECTURE_THEATRE", "Lecture theatre"),
                    ("SEMINAR_ROOM", "Seminar room"),
                    ("CLASSROOM", "Classroom"),
                    ("AUDITORIUM", "Auditorium"),
                    ("LABORATORY", "Laboratory"),
                    ("HALL", "Hall"),
                    ("SPORTS_FACILITY", "Sports facility"),
                    ("LIBRARY", "Library"),
                    ("GALLERY", "Gallery"),
                    ("MEETING_ROOM", "Meeting room"),
                    ("FUNCTION_SPACE", "Function space"),
                    ("OUTDOOR", "Outdoor"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="venuealias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_verified", True)),
                fields=("normalized_alias",),
                name="unique_verified_venue_alias",
            ),
        ),
    ]
