# Generated by Django 5.2.16 on 2026-09-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0006_sync_reviewed_venue_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="location_kind",
            field=models.CharField(
                choices=[
                    ("COMPLEX", "Complex or area"),
                    ("BUILDING", "Building"),
                    ("BLOCK", "Block"),
                    ("HALL", "Residential hall"),
                    ("FACILITY", "Facility"),
                    ("OUTDOOR", "Outdoor place"),
                ],
                default="BUILDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_locations",
                to="venues.building",
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="bookable_by_staff",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="bookable_by_student_organisations",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="level_code",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="venue",
            name="venue_type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building"),
                    ("LECTURE_THEATRE", "Lecture theatre"),
                    ("SEMINAR_ROOM", "Seminar room"),
                    ("CLASSROOM", "Classroom"),
                    ("AUDITORIUM", "Auditorium"),
                    ("LABORATORY", "Laboratory"),
                    ("HALL", "Hall"),
                    ("SPORTS_FACILITY", "Sports facility"),
                    ("LIBRARY", "Library"),
                    ("GALLERY", "Gallery"),
                    ("MEETING_ROOM", "Meeting room"),
                    ("FUNCTION_SPACE", "Function space"),
                    ("TUTORIAL_ROOM", "Tutorial room"),
                    ("DISCUSSION_ROOM", "Discussion room"),
                    ("PROJECT_ROOM", "Project room"),
                    ("COMPUTING_ROOM", "Computing room"),
                    ("STUDIO", "Studio"),
                    ("OUTDOOR", "Outdoor"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
