# Generated by Django 5.2.16 on 2026-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0008_sync_expanded_venue_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="map_positioning_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAPPED_POINT", "Mapped point"),
                    ("GEOMETRY_CENTER", "Geometry centre"),
                    ("PARENT_ANCHOR", "Parent anchor"),
                    ("DERIVED_CENTER", "Derived centre"),
                    ("TEMPORARY_SITE", "Temporary site"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="map_source_identifier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="building",
            name="map_source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="building",
            name="map_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
